name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *' # 8:00 AM IST
    - cron: '00 13 * * *' # 7:30 PM IST
    - cron: '00 06 * * 1-5' # 11:30 PM IST

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman and htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          newman run "In Warranty Flow Collection Copy.postman_collection.json" \
          -e "Dev.postman_environment.json" \
          -d "testdata.csv" \
          -r cli,htmlextra
          -d testdata.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman/index.html
      - name: Newman Report
        if: always() # its going to be executed irrespective of postman tests are passing or failing
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*.html
      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: newman/
   
          
          
      
     
     
